features/cvmfs/rpms.pan
cvmfs-keys has been replaced by cvmfs-config-default which is a dependency of cvmfs.
Also replace nlist with dict.
Fixes #56
=> Do not install cvmfs-keys with cvmfs

features/cvmfs/client.pan
The previous code used a numerical comparison on strings, with incorrect results.
Fixes #59.
Tested, but impact of change on existing systems is unknown.
=> Use pkg_compare_version to compare CVMFS client versions

features/cvmfs/rpms.pan
Fix the RPM to install when the client is 2.1.20. See:
http://cernvm.cern.ch/portal/filesystem/cvmfs-2.1.20
=> Set required RPMs accordingly to cvmfs version

features/cvmfs/client.pan
Allows users to configure extra CVMFS repositories and domains through CVMFS_EXTRA_REPOSITORIES and CVMFS_EXTRA_DOMAINS variables.
It also factorizes the configuration code for existing repositories.
An example for France Grilles repository:
```
variable CVMFS_EXTRA_REPOSITORIES ?= nlist('francegrilles.in2p3.fr',
nlist('server_urls', nlist('CC-IN2P3', 'http://cccrnvmfss1li01.in2p3.fr/cvmfs/francegrilles.in2p3.fr'),
'pubkeys_file', 'cvmfs/keys/francegrilles.in2p3.fr.pub'
),
);
```
@Pansanel: This PR is far better than your #71 ;)
@jouvin: You are right, ncm-metaconfig should be better, in deed. I'll try to have a look at it soon (hopefully).
=> Cvmfs extra repos

filesystem/config.pan, filesystem/config.pan.new
This PR provides the main part of the support for biosboot partitions (https://github.com/quattor/template-library-core/issues/72). It requires https://github.com/quattor/template-library-core/pull/126. The 2 PR altogether fix https://github.com/quattor/template-library-core/issues/72. In addition this PR brings UEFI support in the configuration description (also requires https://github.com/quattor/ncm-lib-blockdevices/issues/71 to be fixed for the actual support).
This PR contains also a some code refactoring/cleanup and several code fixes for long standing bugs uncovered when adding this new feature.
Heavily tested at LAL but tests by other sites are very welcome!
=> filesystem/config: add support for configuring a biosboot partition (legacy BIOS or UEFI)

features/fetch-crl/config.pan, features/fetch-crl/schema.pan
Part of the effort to migrate away from `ncm-sysconfig`.
=> fetch-crl: use metaconfig instead of sysconfig

features/cvmfs/client.pan, features/cvmfs/rpms.pan
Requires https://github.com/quattor/template-library-core/pull/131 first... But would be good to merge it at the same time.
=> cvmfs: use PKG_VERSION_xxx to test pkg_compare_version() return values

hardware/nic/intel/x540.pan
The Intel X540 card is a 10Gb Base-T network adapter.
=> New Intel network card

hardware/nic/mellanox/mt27710.pan
We have a new model of nic @ RAL that is not in the template library, so I am contributing it.
Best wishes,
Bruno
=> Add hardware template for mellanox mt27710 nic.

hardware/cpu/intel/xeon_d_1513n.pan, hardware/cpu/intel/xeon_d_1523n.pan, hardware/cpu/intel/xeon_d_1533n.pan, hardware/cpu/intel/xeon_d_1543n.pan, hardware/cpu/intel/xeon_d_1553n.pan, hardware/cpu/intel/xeon_e6510.pan, hardware/cpu/intel/xeon_e6540.pan, hardware/cpu/intel/xeon_e7520.pan, hardware/cpu/intel/xeon_e7530.pan, hardware/cpu/intel/xeon_e7540.pan, hardware/cpu/intel/xeon_l5618.pan, hardware/cpu/intel/xeon_l5638.pan, hardware/cpu/intel/xeon_l7545.pan, hardware/cpu/intel/xeon_l7555.pan, hardware/cpu/intel/xeon_x6550.pan, hardware/cpu/intel/xeon_x7542.pan, hardware/cpu/intel/xeon_x7550.pan, hardware/cpu/intel/xeon_x7560.pan
These were being ignored due to missing architecture information in ARK,
but this can be inferred from the CPU feature set.
=> Add missing CPUs from Intel's ARK

hardware/cpu/amd/epyc_7251.pan, hardware/cpu/amd/epyc_7281.pan, hardware/cpu/amd/epyc_7301.pan, hardware/cpu/amd/epyc_7351.pan, hardware/cpu/amd/epyc_7351p.pan, hardware/cpu/amd/epyc_7401.pan, hardware/cpu/amd/epyc_7401p.pan, hardware/cpu/amd/epyc_7451.pan, hardware/cpu/amd/epyc_7501.pan, hardware/cpu/amd/epyc_7551.pan, hardware/cpu/amd/epyc_7551p.pan, hardware/cpu/amd/epyc_7601.pan
Based on information from the official spec sheets.
We haven't got any of these yet, so cannot verify that the `model` string matches what `/proc/cpuinfo` will say, but it agrees with the only publicly available dump that I managed to find.
=> Add new AMD EPYC processors

hardware/cpu/amd/opteron_6308.pan, hardware/cpu/amd/opteron_6320.pan, hardware/cpu/amd/opteron_6328.pan, hardware/cpu/amd/opteron_6338p.pan, hardware/cpu/amd/opteron_6344.pan, hardware/cpu/amd/opteron_6348.pan, hardware/cpu/amd/opteron_6366he.pan, hardware/cpu/amd/opteron_6370p.pan, hardware/cpu/amd/opteron_6376.pan, hardware/cpu/amd/opteron_6378.pan, hardware/cpu/amd/opteron_6380.pan, hardware/cpu/amd/opteron_6386se.pan, hardware/cpu/amd/opteron_x2150.pan, hardware/cpu/amd/opteron_x2170.pan, hardware/cpu/amd/opteron_x3216.pan, hardware/cpu/amd/opteron_x3418.pan, hardware/cpu/amd/opteron_x3421.pan
Based on information from AMDs public spec sheets and verified against publicly available `/proc/cpuinfo` dumps.
=> Add last two generations of AMD Opteron CPUs

hardware/cpu/intel/atom_c2558.pan, hardware/cpu/intel/celeron_1047ue.pan
Individually generated with ark2pan.
As requested by @apdibbo, resolves #103.
=> Add CPUs used in Mellanox SN2100 and SN2700 switches

hardware/nic/by_driver/bnx2x.pan
This fixes an issue where the bnx2x is not the primary card.
All network cards have the boot parameters set to 'false', only the bnx2x not. In the case where we want to boot from another nic than bnx2x in a server, we get a configuration issue, as the boot interface is not correctly set.
=> Set bnx2x boot parameter to false

features/docker/config.pan
- In panc 10.7, null is no longer considered an undefined value (see https://github.com/quattor/pan/pull/175)
=> features/docker/config: fix compatibility with panc 10.7

features/fetch-crl/config.pan
v2 support was causing problem when using v3 if `fetch-crl` was the only feature configuring `altlogrotate` component on the machine (invalid `/software/components/altlogrotate` resource due to missing `entries` property). As v2 has been obsolete for years, just remove its support.
=> fetch-crl: remove broken support for very obsolete v2

features/fetch-crl/config.pan, features/fetch-crl/el7/config.pan, features/fetch-crl/rpms-yd.pan, features/fetch-crl/rpms.pan, features/fetch-crl/sl6/config.pan
Workaround for issue https://bugzilla.redhat.com/show_bug.cgi?id=1630027 that will be harmless if/when the bug is fixed.
This PR also removes the support for `fetch-crl` deployment with SPMA.
=> fetch-crl : avoid unnecessary run of fetch-crl-boot

features/cvmfs/client.pan, features/cvmfs/config.pan
- Code of previous version is broken as the test to see if autofs
was already configured doesn't work after including autofs component
- Not managing the required autofs configuration doesn't make sense
- Managing the configuration is harmless as other content in /etc/auto.master
is preserved
=> CVMFS: autofs configuration made mandatory

features/frontier/config.pan
Resolves #128.
Thanks to @almumontiel for reporting.
=> frontier squid: Fix typo in script filename

hardware/harddisk/generic/nvme.pan
In addition to differences in device numbering and namespaces, NVMe devices prefix partitions with `p`.
Requires quattor/template-library-core#203 to add `nvme` to the schema.
=> Add template for NVMe devices

machine-types/core-init.pan, machine-types/core.pan, machine-types/frontier.pan, os/kernel_version_arch.pan, os/version.pan, os/version_db_default.pan
- Initial part factored out in a separate template, core-init.pan, to allow
execution of site specific actions between this initial part and the core configuration
- Ability to delay some part of the configuration, like file systems, in case some site
information must be defined before
- Hook to configure time synchronisation according to site needs (ntp, chrony...)
- Template cleanup
=> machine-types/core refactoring to make it more flexible

filesystem/config.pan
DISK_LV_BY_VG is updated to support setting of logical volume setting, such as type. which sets the raid_type if set.
using the new function lvo_add which supports taking lv options as dict to set size and type. 
Creating raid through LVM is now possible but there appears to be no pan settings to set the logical volume type. this will provide support for this.
fixes #150
=> support for muti options settings for logical volumes

hardware/cpu/amd/epyc_9654.pan
Adding a hardware file for the amd epyc 9654 CPU
=> hardware/cpu/amd: adding epyc_9654

.ci-scripts/indent, .github/workflows/continuous-integration.yaml
This includes adding the indentation checker.
=> workflows: Update and make consistent with template-library-core
